name: aparcamalaga
description: 'Buscador de plazas PMR en Málaga.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.3.6
  http: ^1.2.2
  latlong2: ^0.9.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  flutter_map_tile_caching: ^9.0.1
  go_router: ^14.6.2
  geocoding: ^3.0.0
  flutter_cache_manager: ^3.3.2
  flutter_riverpod: ^2.6.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_lint: ^2.6.2
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon_safe.png
  adaptive_icon_background: "#1F6DB5"
  adaptive_icon_foreground: assets/icons/app_icon_safe.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/icons/app_icon_safe.png
    background_color: "#1F6DB5"
    theme_color: "#1F6DB5"
  windows:
    generate: true
    image_path: assets/icons/app_icon_safe.png
  macos:
    generate: true
    image_path: assets/icons/app_icon_safe.png


